### ISSUE TITLE
Cannot require active_support/core_ext/logger

### ISSUE THREAD

**Issue by smackesey** [nerab/dropcaster#8]
I'm using Ruby 2.2 and the dropcaster CLI command just doesn't seem to work.

    $ dropcaster

>/usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- active_support/core_ext/logger (LoadError)
        from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/dropcaster-0.0.4/lib/dropcaster.rb:10:in `<top (required)>'
        from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/dropcaster-0.0.4/bin/dropcaster:28:in `<top (required)>'
        from /usr/local/var/rbenv/versions/2.2.0/bin/dropcaster:23:in `load'
        from /usr/local/var/rbenv/versions/2.2.0/bin/dropcaster:23:in `<main>'

**Comment by nerab** [comment]
Thanks being the first to try Ruby 2.2! I saw an active_support-related _warning_ when I tried it myself, but no error.

In order to track down your issue, could you please provide a few more details about your environment?

I just added a [Vagrantfile](/nerab/dropcaster/blob/master/test/Vagrantfile) to the project that installs a fresh Ruby 2.2 in a VM and mounts the project in `/dropcaster`. Just run `bundler` in this directory, and dropcaster should run. Can you possibly try this VM and compare it to your environment? 

Thanks for your help!

**Comment by sometxdude** [comment]
I am also getting this error.  I did a clean install of ruby 2.2.0 via rvm, followed by the dropcaster gem install.  I'm on a 64-bit Linux Mint 17.1 machine.

**Comment by nerab** [comment]
Thanks for the report @sometxdude; do I interpret your message correctly that dropcaster works for you with ruby 2.2.0 via rvm, but not with ruby 1.9.3 via rvm?

In both cases, what version does `dropcaster --version` report? Anything before 0.0.5.rc4 is likely to have the bug that is subject of this issue.

**Comment by sometxdude** [comment]
I got the same error w/ the --version command.  However, I can see the version in my gems directory is 0.0.4   This was occuring with both ruby versions 1.9.3 and 2.2.0.   I guess the problem is the gem version seems to default to something very old.  I will try installing the gem from the latest github source.

**Comment by nerab** [comment]
That might explain it. I fixed a number of issues with 0.0.5. Could you please try v0.0.5 that I just pushed?

**Comment by sometxdude** [comment]
That fixed it.  Running 'gem install dropcaster' now installs the 0.0.5 version, and I no longer get the error message.  Works perfect.  Thanks.

**Comment by nerab** [comment]
Thanks for testing that. 

I had missed another update which made Travis unhappy. Therefore 0.0.6 came right after 0.0.5 ;-)
